name: Docker Build
on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Submodules
        shell: bash
        run: |
          git submodule init && git submodule update

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Mangosd Docker image
        run: |
          docker build -t mangosd-zero:latest -f dockercontainer/DockerFile-mangosd .
          docker tag mangosd-zero:latest unentropy/mangosd-zero:latest
          docker push unentropy/mangosd-zero:latest

      - name: Build Realmd Docker image
        run: |
          docker build -t realmd-zero:latest -f dockercontainer/DockerFile-realmd .
          docker tag realmd-zero:latest unentropy/realmd-zero:latest
          docker push unentropy/realmd-zero:latest
